### PR TITLE
Fixed #1121 - Correct spacing between my location & bike-sharing button

### LINKED ISSUE #1121: UI - Bike sharing floating action button incorrect spacing
**Summary:** 

There is incorrect spacing between my location button and bike sharing affecting the main home screen of the application
**Steps to reproduce:** 

1. Open setting and change your location to Tampa Bay.
2. Bike sharing button will appear with the incorrect spacing.

**Expected behavior:** 

Home screen is the main screen of the application we should take care of spacing.

**Observed behavior:** 

Incorrect spacing 

**Device and Android version:** 

API 30 - Google Pixel - Stock / xiaomi note 8 pro

**Screenshots:** 
fab_incorrect

### PR DESCRIPTION
**Pull request by amrhossamdev**
Fixed #1121

- Increasing the margin between the two buttons
- Refactor: Instead of using left and right it's better to use start and end for RTL support.

I have tested different scenarios for the two buttons like opening the arrivals list / using locations that don't have bike-sharing options

Screenshots:

<table>
  <tr>
    <td>correct2</td>
    <td>correct1</td>
    <td>Screenshot_1708878024</td>
  </tr>
</table>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
thanks for tackling this! I think the end result looks great, but I have a couple requests for the code:

1. Please try to make the necessary changes via the XML view instead of the visual designer so that the minimum number of lines of code change as necessary (the visual designer seems to do a lot of indentation changes and property rearranging).
2. I agree with you on the RTL work, but we should adopt the necessary changes across the board instead of in one piece of UI. So, for now, let's keep this consistent and maybe open a task to track full RTL conversion.

**Comment by amrhossamdev** [comment]
Alright, I will fix that, I only did a reformat for the code so a lot of spacing was added and removed.

**Comment by amrhossamdev** [comment]
I will make a new branch for each issue this will merge the new branch into this.

**Comment by amrhossamdev** [comment]
I will close this and open a new PR with changes because I have deleted my main branch to assign for each issue a branch.

**Pull request closed without merging**
