### PR TITLE
fix: donation UI visibility issue

### PR DESCRIPTION
**Pull request by amrhossamdev**
fixes: #1227 

### Video

https://github.com/user-attachments/assets/8375ff9a-4db7-4da0-92d4-0c15e88891e0

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
Can you split the two commits into:

1. target SDK
2. donation UI visibility?

**Comment by amrhossamdev** [comment]
YOC

**Comment by amrhossamdev** [comment]
This pull request addresses the visibility issues with the donation UI. I will submit a separate pull request for the SDK upgrade, which will involve additional changes.

**Review by aaronbrethorst — APPROVED** [review]
looks great! 👍

**Pull request merged**
