### PR TITLE
Finnish translation for enhancement #159 (Add Finnish translation

### PR DESCRIPTION
**Pull request by arirusakko**
Hello

My name is Ari Rusakko and I'm currently installing OBA system to production for the city of Lappeenranta in Finland. This work is based on the work that Turo Ulvinen did earlier. Seems that the translation he made didn't make the android client after all. 

I've made a new version of translations. I have double checked for spelling errors, chosen words and phrases that fit better the mobile phone screen etc. Also this includes the latest changes in the github master.

This pull request only contains the translated files 'strings.xml' and 'arrays.xml' in folder 'values-fi' which are enough to provide the finnish localization on device. I believe this will complete the enhancement #159 :)

-Ari Rusakko (OCTO3)

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @arirusakko for picking this up!  Could you please sign the ICLA [here](https://github.com/OneBusAway/onebusaway-android/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement-icla), and ping me again here once you've completed that?

**Comment by arirusakko** [comment]
Good morning! I've just signed the ICLA.

**Comment by barbeau** [comment]
Thanks @arirusakko, looks good!

What is your timeline for launching OBA in production in Lappeenranta (i.e., when would you want/need the Finnish translation available in the app on Google Play)?

Also, a heads up that there is a lot of work done in the develop branch for a user interface overhaul, which introduces a number of new strings:
https://github.com/OneBusAway/onebusaway-android/tree/develop

I'd suggest going ahead and doing a translation of those as well, and submitting a new PR against the develop branch.  There will likely still be a few more strings added as we refine the UI, but hopefully not many.

**Comment by arirusakko** [comment]
Well... The launch should be as soon as we get this thing running. But there are other problems too, like getting valid gtfs data from our data provider. Also I've just started installing the OBA system on our server and to be honest, the documentation leaves a lot to be desired. I suspect tackling this installation of OBA webapp+xwiki with mysql support in addition to setting up our custom gps data provider is going to take a while.

So it's safe to assume that next week we are able to do some testing, but for that I can always build my own client. Maybe after that we distribute the gps devices to buses and perhaps after that we can finally go public.  Soo I'm pulling an estimate of 1-3 weeks out of my hat. 

But you can put it as soon as you can to app store, I assume finnish localization causes no harm :)

**Comment by barbeau** [comment]
@arirusakko Ok, thanks.  Yes, the Finnish localization shouldn't interfere with anything else.  However, we just pushed a new update a few days ago (and a series of betas just before that), and I'd like to avoid spamming users with updates if possible.  On top of that, my activity will be reduced over the next two months as I'm on parental leave :).  So, please ping me here again as you get closer to launch and we can make sure it goes out in a release prior to that.

**Comment by arirusakko** [comment]
Fair enough. I'll start shouting when I get some visibility on the schedule. Doesn't really help me that there are like three separate companies involved in this installation, in addition to OBA itself.

**Comment by barbeau** [comment]
Sounds good!  Good luck, I know coordinating with everybody is challenging, to say the least.

**Comment by arirusakko** [comment]
Hello again.

We're closing in to the moment where we apply for the experimental region status. Is it possible to get the finnish translation released for the android app?

**Comment by barbeau** [comment]
Sure - I'll do a release early next week.  Sorry this has been slow going
out, I've been on Parental Leave since April, but return next week.

**Comment by arirusakko** [comment]
Ok, no worries. Early next week sounds great. Our GTFS data starts to be valid 1st of June anyway.
...and our data provider still hasn't managed to provide us with kosher data. 

So end of next week will be probably the earliest we dare to apply for the experimental region status. By the way, do you have any idea how long that process takes?

**Comment by barbeau** [comment]
Shouldn't take more than a day or so.  I'll just need to verify your
installation is working and then process a few things to include your
region in the Regions API response.

Ok, no worries. Early next week sounds great. Our GTFS data starts to be
valid 1st of June anyway.
...and our data provider still hasn't managed to provide us with kosher
data.

So end of next week will be probably the earliest we dare to apply for the
experimental region status. By the way, do you have any idea how long that
process takes?

—
Reply to this email directly or view it on GitHub
<https://github.com/OneBusAway/onebusaway-android/pull/253#issuecomment-106720185>
.

**Comment by barbeau** [comment]
@arirusakko I was prepping the release, and realized that the "What's New" popup that is shown after updating the app needs to be updated in Finnish.  Current English text is:

* Finnish translation
* Auto-hide keyboard when leaving Search tab

If you can provide the Finnish equivalent in a comment here I'll add it myself to the values-fi strings.xml.

**Comment by arirusakko** [comment]
Hi
Those two are:
- Suomenkielinen käännös
- Näppäimistön automaattinen piilotus hausta poistuttaessa.

2.6.2015 5.12 ip. Sean Barbeau <notifications@github.com> kirjoitti:@arirusakko I was prepping the release, and realized that the "What's New" popup that is shown after updating the app needs to be updated in Finnish.  Current English text is:

Finnish translationAuto-hide keyboard when leaving Search tab

If you can provide the Finnish equivalent in a comment here I'll add it myself to the values-fi strings.xml.

**Comment by barbeau** [comment]
@arirusakko Thanks!  I just released v1.7.9 to beta, which includes the Finnish translation - it should be visible in the next hour or so on Google Play.  Could you please sign up for the beta releases if you haven't already (see [instructions here](https://github.com/OneBusAway/onebusaway-android/blob/master/BETA_TESTING.md)), and make sure everything looks ok?

**Comment by arirusakko** [comment]
Looks ok with quick glance...
2.6.2015 7.00 ip. Sean Barbeau <notifications@github.com> kirjoitti:@arirusakko Thanks!  I just released v1.7.9 to beta, which includes the Finnish translation - it should be visible in the next hour or so on Google Play.  Could you please sign up for the beta releases if you haven't already (see instructions here), and make sure everything looks ok?

**Comment by barbeau** [comment]
Ok, thanks.  If everything continues to look ok I'll graduate this to full release and increase rollout % over the next few days.

**Comment by arirusakko** [comment]
I went through the rest of the UI texts using our test backend and everything is looking still good. :+1:

**Comment by barbeau** [comment]
Awesome, thanks!

**Pull request merged**
