### PR TITLE
Make ES "My Profile" screen a fragment instead of activity

### PR DESCRIPTION
**Pull request by acrown-msft**
Load Embedded Social fragments, rather than activities, from the OBA navigation drawer.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by barbeau** [comment]
@acrown-msft It looks like this PR is for changing the "M y Profile" screen from an Activity to `MyProfileFragment`, and then removing the logic required for handling social Activities via the navigation drawer, right?  I just want to make sure I get the merged commit title right.

**Comment by barbeau** [comment]
Ok, thanks.  Does this bump in library version fix the bug you mentioned in the ES SDK fragment handlers, or is that still outstanding?  If outstanding, could you please open an new issue so we can track that?

**Comment by acrown-msft** [comment]
The bump in library version fixes the issue of having multiple listeners responding to the same event.

**Comment by barbeau** [comment]
Great, thanks!

**Comment by barbeau** [comment]
Thanks @acrown-msft!

**Pull request merged**
