### PR TITLE
Add ic_launcher_round images

### PR DESCRIPTION
**Pull request by dblackker**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

**Note: testBuildTripOptions failed, but is unrelated to asset changes**
```
// testBuildTripOptions
junit.framework.AssertionFailedError: expected:<8> but was:<7>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at org.onebusaway.android.util.test.UIUtilTest.testBuildTripOptions(UIUtilTest.java:223)
```

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by dblackker** [comment]
This PR is to make launcher icons look better.
https://developer.android.com/about/versions/nougat/android-7.1#circular-icons

**Comment by dblackker** [comment]
@barbeau I'll do this when I get a chance.

**Comment by dblackker** [comment]
@barbeau Here are the before and after. Notice the round icon fills the entire round placement.

onbuse-after-round-icon
onebus-before-round-icon

**Comment by barbeau** [comment]
@dblackker Thank you very much for working on this, and sorry it's taken so long to review! 

I ended up adding full adaptive icon support for OneBusAway in https://github.com/OneBusAway/onebusaway-android/commit/53fc0032258e28528fdf8f073411278a3a37d8bd, which includes the assets for the round launch icon that will align with the other adaptive icon assets. So I'm going to close this PR as it's superseded by the adaptive icons. I really appreciate you taking the time to put this together though!

**Pull request closed without merging**
