### PR TITLE
Add bug fixes to "What's New?"

### PR DESCRIPTION
**Pull request by barbeau**
@cagryInside Could you please test this (uninstall the app, and install this to see "What's New?" screen) on your devices?

I'm a little concerned about the height of the dialog, and it potentially cascading off the screen on small screen devices.  Please check with your smaller screen devices and make sure we don't block access to the "CLOSE" button.  Thanks!

image

### CODE REVIEW

**Comment by cagryInside** [comment]
> @cagryInside Could you please test this (uninstall the app, and install this to see "What's New?" screen) on your devices?

Tested this with HTC evo 3D and HTC evo shift. It looks good:

device-2016-05-12-101215

**Comment by barbeau** [comment]
@cagryInside If you rotate to landscape orientation is the "Close" button still accessible?

**Comment by cagryInside** [comment]
> @cagryInside If you rotate to landscape orientation is the "Close" button still accessible?

Yes, I also added more items:

device-2016-05-12-123050
device-2016-05-12-123107

**Comment by barbeau** [comment]
@cagryInside Awesome, thanks!

**Pull request merged**
