### PR TITLE
WIP - Issue #155 - UI re-design

### PR DESCRIPTION
**Pull request by barbeau**
Please don't merge - this is a work-in-progress pull request so others can keep track of progress and provide feedback on the UI re-design (#155), including Maps API v2 implementation (https://github.com/OneBusAway/onebusaway-android/issues/56) and StopInfo project (https://github.com/OneBusAway/onebusaway-android/issues/103).

I'm updating this top comment with progress as we go.

To try out the UI re-design, please [register as an alpha tester](https://github.com/OneBusAway/onebusaway-android/blob/master/BETA_TESTING.md#register-as-an-alpha-tester)!

**Known issues:**
* See bugs under [public v2.0.x release milestone](https://github.com/OneBusAway/onebusaway-android/milestones/Public%20v2.0.x%20release)

**TODO:**
* See enhancement issues under [public v2.0.x release milestone](https://github.com/OneBusAway/onebusaway-android/milestones/Public%20v2.0.x%20release)

Feedback is appreciated!  Screenshots are below.

image

@caitbonnar APK to install and test StopInfo is linked above in this PR.

### CODE REVIEW

**Comment by barbeau** [comment]
Hi all!  For anyone following this PR but not the original issue, I [just posted](https://github.com/OneBusAway/onebusaway-android/issues/155#issuecomment-131239723) some of our recent UI redesign progress there.  If you'd like to get this alpha version via Google Play in the next week or so, please [sign up for alpha updates](https://github.com/OneBusAway/onebusaway-android/blob/master/BETA_TESTING.md#register-as-an-alpha-tester)!

**Comment by barbeau** [comment]
I've maintained a TODO list in the first comment on this PR - as we approach a public release of v2.0.x and this new UI, I'm going to move some of these items into individual issues so I can organize them as being completed by the [v2.0.x public release](https://github.com/OneBusAway/onebusaway-android/milestones/Public%20v2.0.x%20release), or a future [v2.1 release](https://github.com/OneBusAway/onebusaway-android/milestones/v2.1).  So, beware the firestorm of new issues - the v2.0.x public release issues should be closed relatively soon, though.

**Comment by barbeau** [comment]
Alright everyone, we're closing in fast on a v2.0 release with the new UI.  So, I'm going to bring this long, winding WIP PR to a close :).

A few things from the original mockup/concept didn't make the v2.0 cut, so I've pulled some of the items out into their own issues for future work/release, including:
* [Improved search (including integration of recent stops/routes)](https://github.com/OneBusAway/onebusaway-android/issues/309)
* [Nearby routes](https://github.com/OneBusAway/onebusaway-android/issues/352)

Thanks to everyone for their time and feedback!!  I really appreciate it, and I think it improved the UI overhaul tremendously.  If I missed anything or you have more feedback, please feel free to comment here, on one of the remaining issues, or open a new issue.

All UI redesign work is currently in the `develop` branch, so I'll be merging this into the master branch in the very near future.  There are some conflicts resulting from some intermediate/hotfix releases, so I won't be merging this PR directly via Github.  I'll merge manually instead.  However, this PR will contain all the commits for the UI redesign, if anyone wants to revisit it at some point.

Closed via work in `develop` branch, to be merged into master shortly.

**Comment by paulcwatts** [comment]
Congrats! This is a huge leap forward!

**Comment by barbeau** [comment]
@paulcwatts Thanks!  And thanks to all your work over the years that made this app possible.  It was quality work - there are still huge chunks of Paul-code in v2.0 of the app :).

**Comment by caitbonnar** [comment]
Wonderful! Congrats and job well done!

**Pull request closed without merging**
