### PR TITLE
Fixed #837 - Added margin in route_list_item.xml and stop_list_item.x…

### LINKED ISSUE #837: Action bar title is slightly offset from the material design guidelines
**Summary:** 

After updating to `compileSdkVersion 26`, the action bar title shifted slightly to the right.  Now, it's no longer exactly aligned with the lists - for example, starred stops:

image

Prior to `compileSdkVersion 26` the "Starred stops" title was exactly aligned with the stop names (i.e., at the red line).

This may be related to the fact that we're still using the deprecated `ActionBarCompat` instead of the toolbar.

**Steps to reproduce:** 

1. Star a stop
1. Go to the "Starred stops" view in the main HomeActivity

**Expected behavior:** 

Action bar title should be exactly aligned with the stop names

**Observed behavior:** 

Action bar title has shifted right slightly and is no longer aligned with the stop name

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 beta

**Screenshots:** 

See above

### PR DESCRIPTION
**Pull request by GajananPalepwad**
…ml to align with the header title

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by GajananPalepwad** [comment]
@aaronbrethorst plz check this i have redid the pr

**Comment by GajananPalepwad** [comment]
image
i have signed but its showing not signed

**Comment by aaronbrethorst** [comment]
@GajananPalepwad thank you for tackling this and submitting a pull request. After reviewing where Android is today in terms of UI design, I think it actually makes more sense for us to close the original ticket as 'not planned,' instead of incorporating it into the product. Apologies for having you spend your time on this, but I appreciate the dedication. Please feel free to reach out to me before tackling something else in case this happens again.

**Comment by GajananPalepwad** [comment]
> @GajananPalepwad thank you for tackling this and submitting a pull request. After reviewing where Android is today in terms of UI design, I think it actually makes more sense for us to close the original ticket as 'not planned,' instead of incorporating it into the product. Apologies for having you spend your time on this, but I appreciate the dedication. Please feel free to reach out to me before tackling something else in case this happens again.

Ok sir no problem

**Pull request closed without merging**
