### PR TITLE
Fix #105 - Implement Google Analytics - develop rebase

### LINKED ISSUE #105: Add Google Analytics
As discussed in https://github.com/OneBusAway/onebusaway-iphone/issues/263#issuecomment-35123537, we'd like to add Google Analytics to both the OBA iOS and Android apps to have better information about how they are being used.  As recommended in [GA Best Practices](https://support.google.com/analytics/answer/2587087), we plan to use the same property for both apps:

>*Track different platforms of an app in the same property.*
If you’ve developed the same app for different platforms (i.e., MyApp for Android and MyApp for iOS), track them in the same property. You can then set up [new views](https://support.google.com/analytics/answer/2614741) to organize and compare the performances in your Google Analytics reports. If your iOS and Android apps differ greatly in performance or usage, you might want to track each platform in separate properties.

Tracking data is needed for research projects such as [StopInfo](https://github.com/OneBusAway/onebusaway-android/issues/103).

### PR DESCRIPTION
**Pull request by cagryInside**
I rebased my ga development branch on top of the OBA develop branch.

### CODE REVIEW

**Comment by barbeau** [comment]
@cagryInside Thanks!  Looks like this is failing on Travis though on the Amazon build flavor:
~~~
onebusaway-android:compileAmazonDebugJava/home/travis/build/OneBusAway/onebusaway-android/onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:605: error: cannot find symbol
            Location myLocation = LocationUtil.getLocation2(this, mLocationClient);
~~~

Could you please take a look?  GA should still work on Fire Phone so we will need to make sure that flavor is properly outfitted.  Check readme for how to build Amazon flavor.  I can get you the device on Tues to test with to make sure it reports properly.  We will also be able to setup the view filtering in OBA GA console to split out Amazon devices from normal Android.

**Comment by barbeau** [comment]
Just realized that I missed a step in Read me for building Amazon flavor.  Look at the Fire Phone issue, halfway down comments is a mvn command you need to run to install Amazon Maps AAR library to your local Maven repo.

**Comment by cagryInside** [comment]
@barbeau I think I fixed the problem in my local. But lets test on amazon device tomorrow morning.

**Comment by yaroslavd** [comment]
I just downloaded and sideloaded the apk. Looking good so far! Thanks for all the effort!

On February 9, 2015, at 8:11 AM, Cagri Cetin <notifications@github.com> wrote:

@barbeau I think I fixed the problem in my local. But lets test on amazon device tomorrow morning.

**Comment by barbeau** [comment]
@cagryInside I think you just need to rename `mLocationClient` to `mGoogleApiClient` in the new code in HomeActivity.  You can test locally to see if the tests pass with `gradlew connectedCheck` from the command line.

**Comment by cagryInside** [comment]
@barbeau Yes, I already tested. I saw the tests passed except the fallowing:
```
onebusaway-android:connectedAndroidTestAmazonDebug FAILED

FAILURE: Build failed with an exception
* What went wrong:
Execution failed for task ':onebusaway-android:connectedAndroidTestAmazonDebug'.
> com.android.builder.testing.api.DeviceException: java.lang.RuntimeException: No connected devices!
```
I think it's ok since there is no device connected.

**Comment by barbeau** [comment]
We can meet tomorrow to run on the Fire - `gradlew connectedCheck` passes for both Amazon and Google build variants when I have my LG G3 connected.  Try connecting your device and running `gradlew connectedCheck`.

**Comment by cagryInside** [comment]
@barbeau GA development tested on Amazon fire phone and it works fine. But, while I was testing, I found a bug. There is a bug for google analytics API with new google play services version (6.5.87). Sometimes ```GoogleAnalytics.getInstange()``` method was locking up. Proposed solution (http://stackoverflow.com/a/27503059/701325) applied to fix the bug.

**Comment by barbeau** [comment]
Thanks @cagryInside!  Thanks for spotting the GA bug.  One question related to this - in the proposed SO solution, it removes the following from the manifest:

~~~
meta-data android:name="com.google.android.gms.analytics.globalConfigResource" android:resource="@xml/global_tracker"
~~~

My understanding is that this removes the automated XML config of the global tracker.

But, from a quick look I don't think I see a place where we manually config the global tracker?

For example, in a comment on that solution, one user says to replace the XML config with the following manual config:

~~~
GoogleAnalytics googleAnalytics = GoogleAnalytics.getInstance(mContext); googleAnalytics.setLocalDispatchPeriod(30); mGATracker = googleAnalytics.newTracker(mTrackerId); mGATracker.setSessionTimeout(300); mGATracker.enableExceptionReporting(true); 
~~~

Can you confirm that the dual tracking (global and local) both work in this PR?  Am I missing the manual config somewhere?

**Comment by cagryInside** [comment]
> Am I missing the manual config somewhere?

@barbeau the manual config stated in app_tracker and global_tracker xml files. And in the runtime, the method in ```Application ``` class returns the tracker:

```
 public synchronized Tracker getTracker(TrackerName trackerId) {
+        if (!mTrackers.containsKey(trackerId)) {
+            GoogleAnalytics analytics = GoogleAnalytics.getInstance(this);
+            Tracker t = (trackerId == TrackerName.APP_TRACKER) ? analytics.newTracker(R.xml.app_tracker)
+                    : (trackerId == TrackerName.GLOBAL_TRACKER) ? analytics.newTracker(R.xml.global_tracker)
+                    : analytics.newTracker(R.xml.global_tracker);
+            mTrackers.put(trackerId, t);
+        }
+        return mTrackers.get(trackerId);
+    }
```

> Can you confirm that the dual tracking (global and local) both work in this PR?

I also tested for android and amazon phones. Dual tracking works fine.

**Comment by barbeau** [comment]
@cagryInside Ok, great, thanks!  So what (if anything) did the extra text in the manifest that we removed do?

**Comment by cagryInside** [comment]
@barbeau Actually, we were using it to log screen visits automatically until we decide to use two different trackers. 

Before, with one tracker;
```
     public static void reportActivityStop(Activity activity) {   	
       if (isAnalyticsActive()) {
            GoogleAnalytics.getInstance(activity).reportActivityStop(activity);
        }
    }

  public static void reportActivityStart(Activity activity) { 
      if (isAnalyticsActive()) {
           GoogleAnalytics.getInstance(activity).reportActivityStart(activity);
        }
     }		   
  } 
```

Then we implement two tracker instead of the first implementation:

```
  Tracker tracker = Application.get().getTracker(Application.TrackerName.APP_TRACKER);		         
         tracker.setScreenName(activity.getClass().getSimpleName());		         
         tracker.send(new HitBuilders.ScreenViewBuilder().build());	
         Tracker tracker2 = Application.get().getTracker(Application.TrackerName.GLOBAL_TRACKER);		         
         tracker2.setScreenName(activity.getClass().getSimpleName());		      
         tracker2.send(new HitBuilders.ScreenViewBuilder().build());
```
PS: in this configuration, we don't need that text anymore.

**Comment by barbeau** [comment]
Ok, great, thanks!

**Pull request merged**
