### PR TITLE
Fix #783 - Support Android Studio 3.0 and Gradle Plugin v3

### LINKED ISSUE #783: Won't build in Android Studio 3.0
Trying to import the project for the first time. I'm getting this error:

> Error:(261, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=agencyXAmazonDebug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

The line it's complaining about is [build.gradle L260](https://github.com/OneBusAway/onebusaway-android/blob/ede3eca30d174404e1f6abac6d52a8198b4c29a0/onebusaway-android/build.gradle#L260-L261).

It's preventing me from configuring Build Variants, since it's failing the entire Gradle sync.

### PR DESCRIPTION
**Pull request by barbeau**
~~**Please don't merge - WIP**~~

Initial work towards supporting Android Studio 3.0 and Android Gradle Plugin v3

Posts that were useful in resolving issues:
* https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#aapt2_resource_naming
* https://stackoverflow.com/questions/44239235/android-gradle-3-0-0-alpha2-plugin-cannot-set-the-value-of-read-only-property/44265374#44265374
* https://stackoverflow.com/a/47132142/937715
* https://stackoverflow.com/questions/42374151/all-com-android-support-libraries-must-use-the-exact-same-version-specification

TODO:
- [x] ArrivalsListHeader - Discussion bubble icon isn't material design.  Looks like there are local vector image resources as well as raster images in the ES SDK.  Need to figure out which is actually being shown in project.
- [x] Change from above solution - Change `es_oba_ic_comment` to use same name as SDK `es_ic_comment` for material design comment PNG icons (i.e., delete XML drawable and replace with PNG drawables)
- [x] Different Android support library versions are still being reported in build.gradle inspection, coming from ES SDK:
~~~
\--- com.acrowntest.test:sdk:0.0.37
     +--- net.openid:appauth:0.3.0
     |    \--- com.android.support:customtabs:24.0.0
~~~
Project still compiles and runs even though error is shown in Android Studio, so this doesn't necessarily block this PR but I'd like to resolve it. I've opened an issue on the ES SDK to track updating the OpenID library to a new version - https://github.com/Microsoft/EmbeddedSocial-Android-SDK/issues/67.
EDIT - I've moved this issue to https://github.com/OneBusAway/onebusaway-android/issues/843.
- [x] Amazon build is failing [on Travis](https://travis-ci.org/OneBusAway/onebusaway-android/builds/320412500?utm_source=github_status&utm_medium=notification) with `/home/travis/build/OneBusAway/onebusaway-android/onebusaway-android/build/intermediates/manifests/full/obaAmazon/debug/AndroidManifest.xml:25: error: unknown element <uses-amzn-sdk> found.`
- [x] Fix `Resources$NotFoundException: File res/drawable/bike_marker_small.xml` on API 19 (see https://github.com/OneBusAway/onebusaway-android/pull/835#issuecomment-357053368)
- [x] More testing to make sure nothing else broke
- [x] Seems like Embedded Social features may be broken?  When trying to use them I'm seeing “You can still post while offline” (see bottom bar at bottom) (using Samsung Galaxy S8+ w/ Android 8.0 beta). UPDATE - Neither I or Alex can repro now - consider a fluke:

image

### CODE REVIEW

**Comment by barbeau** [comment]
@acrown-msft I noticed that for the drawables `es_ic_comment.xml`, there is a version in OBA as well as in the ES SDK:
image

After I updated to Android Studio 3.0, it flagged the `android:fillColor` as not being able to use colors defined as resources (only the direct hex values were supported).  To resolve this, I added `vectorDrawables.useSupportLibrary = true` to `build.gradle` as specified [here](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html#vector-drawables-backward-solution).  

However, now I see the old non-material design speech bubble:

image

I can delete the version in OBA, but then I get this warning:

image

I think this should probably be a public resource in the ES SDK?

Even after this, though, I still see the old non-material design speech bubble.  

As a reminder here's what the material design version looks like in the master branch:

image

Any pointers as to which resources are controlling this, and which version of the icons are defined where?

I'll keeping looking...

**Comment by barbeau** [comment]
Ah, got it - it looks like the ES SDK library version was overriding the OBA application version.  If I rename the OBA version to `es_oba_ic_comment.xml` and change the code to reference this drawable resource, then the material design icon is back:

image

**Comment by barbeau** [comment]
@acrown-msft I found this error report / stack trace in the Android Developer Console - I believe this was from my device when I was testing a build of this branch as a release:

~~~
java.lang.NoClassDefFoundError: 
  at net.openid.appauth.AuthorizationService.<init> (AuthorizationService.java:101)
  at com.microsoft.embeddedsocial.c.d.<init> (Unknown Source:26)
  at com.microsoft.embeddedsocial.ui.c.bk.e (Unknown Source:4)
  at com.microsoft.embeddedsocial.ui.c.bk.b (Unknown Source)
  at com.microsoft.embeddedsocial.ui.c.bk.c (Unknown Source)
  at com.microsoft.embeddedsocial.ui.c.bo.onClick (Unknown Source:2)
  at android.view.View.performClick (View.java:6855)
  at android.view.View$PerformClick.run (View.java:26047)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6972)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:93)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
~~~

This may be the cause of the "You can still post while offline" error message in the earlier posted screenshot.

As I mentioned in the Hangout, it may be simple to fix this by changing `build.gradle` ES SDK dependency from `implementation` to `api`, as discussed in:
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

**Comment by acrown-msft** [comment]
I run into a crash on boot with an emulator running API 19.  It seems to be related to loading a vector drawable.  Stack trace below:

<pre>
E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.joulespersecond.seattlebusbot, PID: 3386
  android.content.res.Resources$NotFoundException: File res/drawable/bike_marker_small.xml from drawable resource ID #0x7f08005f. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
      at android.content.res.Resources.loadDrawable(Resources.java:2101)
      at android.content.res.Resources.getDrawable(Resources.java:700)
      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:353)
      at org.onebusaway.android.map.googlemapsv2.bike.BikeStationOverlay.createBitmapFromShape(BikeStationOverlay.java:195)
      at org.onebusaway.android.map.googlemapsv2.bike.BikeStationOverlay.<init>(BikeStationOverlay.java:87)
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setupBikeStationOverlay(BaseMapFragment.java:474)
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setMapMode(BaseMapFragment.java:515)
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.initMapState(BaseMapFragment.java:343)
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.initMap(BaseMapFragment.java:325)
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onMapReady(BaseMapFragment.java:291)
      at com.google.android.gms.maps.SupportMapFragment$zza$1.zza(Unknown Source)
      at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
      at android.os.Binder.transact(Binder.java:361)
      at com.google.android.gms.maps.internal.aq.a(:com.google.android.gms.DynamiteModulesB:5)
      at com.google.maps.api.android.lib6.impl.bb.run(:com.google.android.gms.DynamiteModulesB:5)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5017)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
      at dalvik.system.NativeStart.main(Native Method)
   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
      at android.content.res.Resources.loadDrawable(Resources.java:2097)
      at android.content.res.Resources.getDrawable(Resources.java:700) 
      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:353) 
      at org.onebusaway.android.map.googlemapsv2.bike.BikeStationOverlay.createBitmapFromShape(BikeStationOverlay.java:195) 
      at org.onebusaway.android.map.googlemapsv2.bike.BikeStationOverlay.<init>(BikeStationOverlay.java:87) 
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setupBikeStationOverlay(BaseMapFragment.java:474) 
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setMapMode(BaseMapFragment.java:515) 
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.initMapState(BaseMapFragment.java:343) 
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.initMap(BaseMapFragment.java:325) 
      at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onMapReady(BaseMapFragment.java:291) 
      at com.google.android.gms.maps.SupportMapFragment$zza$1.zza(Unknown Source) 
      at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source) 
      at android.os.Binder.transact(Binder.java:361) 
      at com.google.android.gms.maps.internal.aq.a(:com.google.android.gms.DynamiteModulesB:5) 
      at com.google.maps.api.android.lib6.impl.bb.run(:com.google.android.gms.DynamiteModulesB:5) 
      at android.os.Handler.handleCallback(Handler.java:733) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:136) 
      at android.app.ActivityThread.main(ActivityThread.java:5017) 
      at java.lang.reflect.Method.invokeNative(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:515) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
      at dalvik.system.NativeStart.main(Native Method) 
</pre>

**Comment by barbeau** [comment]
@acrown-msft Thanks, I'll check it out!

**Comment by barbeau** [comment]
Looks like Amazon no longer requires the `<uses-amzn-sdk` element in the manifest, so we can remove that - see:
https://forums.developer.amazon.com/articles/90051/removing-the-tag-from-your-android-manifest.html

**Comment by barbeau** [comment]
@acrown-msft I can't repro the "offline" issue that I experienced before, so let's consider it a fluke.  I'll open another issue if I can reproduce.

**Comment by barbeau** [comment]
I've moved the conflicting Android support library message issue to https://github.com/OneBusAway/onebusaway-android/issues/843, as Android Studio flags this as an error but the project still runs and builds fine.

**Comment by barbeau** [comment]
@acrown-msft I changed to using PNGs to override the ES SDK drawables instead of a vector drawable.

Interestingly, it still shows the ES SDK drawable in Android Studio preview:

image

...but it does show the correct OBA Android PNG drawable in the app when running:

image

So, we can move forward with the strategy of using PNGs in the application project with the same resource name as the PNGs in the ES SDK.

**Comment by barbeau** [comment]
Hmmm...Travis builds are failing after bumping project to compileSdkVersion 27 to support vector fix for loading bikeshare marker (https://travis-ci.org/OneBusAway/onebusaway-android/builds/330555748?utm_source=github_status&utm_medium=notification) with:

~~~
* What went wrong:
A problem occurred configuring project ':onebusaway-android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
~~~

**Comment by barbeau** [comment]
Looks like https://github.com/travis-ci/travis-ci/issues/8874 might be the Travis fix for the SDK 27 license issue.

**Pull request merged**
