### PR TITLE
Fix #264 - Fix stop/trip problem reporting API requests

### LINKED ISSUE #264: Improve stop/trip problem reporting API requests
Looks like there is an issue with how OBA Android is sending REST API requests for stop/trip problem reporting - see https://github.com/OneBusAway/onebusaway-application-modules/issues/126#issuecomment-94544761.

If we can confirm that the documented APIs are currently working, we should change to using that method:

* http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-stop.html
* http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-trip.html

### PR DESCRIPTION
**Pull request by cagryInside**
This PR fixes issue #264.  

Get requests are now used to report stop/trip problems instead of post requests.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @cagryInside!  My only comment is that we may want to use the normal GET request construction in OBA that's used for the other HTTP requests instead of turning a POST into a GET, for two reasons:

1. We may have a genuine need for a POST in the future - currently it seems like that's what is offered from the methods, but internally we're turning it into a GET.
2. We have [a number of unit tests](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/androidTest/java/org/onebusaway/android/io/test/UrlFormatTest.java) to check to make sure all types of OBA base URLs are formatted correctly, when using the internal GET construction - we've hit issues in the past with base URLs that have port numbers, spaces in agency names, partial paths, etc.  I'd like to confirm via those tests that the problem reporting URLs are formatted correctly.

We can discuss more in meeting today.

**Comment by barbeau** [comment]
Actually, looks like there are some unit tests for this you can build on from https://github.com/OneBusAway/onebusaway-android/pull/382.

**Comment by cagryInside** [comment]
@barbeau I updated the PR with new test cases.

**Comment by barbeau** [comment]
@cagryInside Thanks, looks good!

**Pull request merged**
