### PR TITLE
Update spanish translations for trip planning

### PR DESCRIPTION
**Pull request by themonki**
**Please don't merge**

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Sign the [electronic OBA ICLA](https://docs.google.com/forms/d/12jV-ByyN186MuPotMvxJtNKtSaGGTnEHm8rXomM2bm4/viewform)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks for working on this @themonki!  FYI, there are some strings that have been added and/or changed to `strings.xml` and `array.xml` after the initial pull request that added trip planning info, so I'd use the current `master` branch as reference for the translation.

**Comment by barbeau** [comment]
Also, if you want to test the translation in the app, you'll need to use the Tampa Bay region, as it's currently the only one that supports trip planning.

**Comment by themonki** [comment]
Yes, I use master branch because I note some changes. That is because is WIP. 

Currently I deploy a local OTP server, so I am testing, but I will testing on Tampa Bay too. I want to check if on trip planing the translations is acorrding to some terms and layout, because some texs are "big".

**Comment by barbeau** [comment]
Just curious - are you using the master branch of OTP server?  If so, does
it work with OBA?

**Comment by themonki** [comment]
No, I am using the '[Basic Usage](http://docs.opentripplanner.org/en/latest/Basic-Usage/)'  version 0.19 of the jar. I'm deploy local and test on my region data.

**Comment by themonki** [comment]
@barbeau currently I see a error when try to tip directions:

`07-21 09:15:19.038 11513-11513/org.agencyx.android E/TripPlanFragment: Error getting geocoding results
`

I dont know why, just the the google dialog closes. I testing on Tampa Bay and have the same issue, dont know if same error. I'm using the brand agencyX for Tampa Bay and agencyY for the local region.

I can use current location and for now I can verify some translations. I want to verify the translations on the detail view:

image

**Comment by barbeau** [comment]
>@barbeau currently I see a error when try to tip directions:
07-21 09:15:19.038 11513-11513/org.agencyx.android E/TripPlanFragment: Error getting geocoding results 

@themonki Can you please open a new issue for this with repro steps?  I'm not sure I understand what's happening from the above description.

**Comment by themonki** [comment]
@barbeau I rebase and squash with master. Is ready for merge.

**Comment by barbeau** [comment]
Awesome, thanks @themonki!  Great to get this translated!

**Pull request merged**
