### PR TITLE
Arrivals List Item formats ETAs in hours if time is greater than 60 minutes.

### PR DESCRIPTION
**Pull request by azizmb9494**
An Arrival's ETA is formatted as "hh:mm" hrs (hh being hours, mm being minutes) if the ETA for a bus is greater than 60 minutes.

### CODE REVIEW

**Comment by barbeau** [comment]
hey @azizmb9494!  Could you please sign the [ICLA](https://docs.google.com/forms/d/12jV-ByyN186MuPotMvxJtNKtSaGGTnEHm8rXomM2bm4/viewform)?

Also, do you have a screenshot of this?  My one concern is listing full hrs+min would take up quite a bit of screen real estate, especially on smaller screen devices.

**Comment by azizmb9494** [comment]
Hey @barbeau! I thought I signed it last night, but just in case I didn't, submitted it again! 
I will submit one shortly. 

I noticed that on larger ETAs (e.g, where the minutes are in the 100s), this might look tidier while taking up almost the same amount of space. I haven't checked it out on ETAs where the minutes are in the 1000s just yet though.

**Comment by azizmb9494** [comment]
Here are two screenshots: 
screenshot_20160411-172533
screenshot_20160411-172624

**Comment by barbeau** [comment]
@azizmb9494 Thanks!  I believe we'd want to present the ETA as "1 hr 5 min" instead of clock format, so it doesn't get confused with a clock time (if you tap on a stop at night that doesn't have any arrivals, you can see how it looks).  To do that, you have to add " hr " to the label, which is where we start getting squished for room.

**Comment by barbeau** [comment]
@azizmb9494 Thanks again for submitting this.  As discussed, I'm going to close this one out, due to the spacing issues.  But we welcome future contributions!

**Pull request closed without merging**
