### PR TITLE
Fix #330 - Change to runtime permissions

### LINKED ISSUE #330: Move to runtime permissions model for Android 6.0
In Android 6.0, there are new runtime permissions, instead of install-time permissions.  We'll need to move to runtime permissions at some point in the near future.

According to this article:
http://www.fulcrumapp.com/blog/fulcrum-android-and-marshmallow-runtime-permissions/

...runtime permissions aren't enforced until we change `targetSdkVersion` to 23 or higher.

Above article has good description of which permissions are "NORMAL" and don't require user prompts, and which are "DANGEROUS" and require user prompts - it points to this link:
http://developer.android.com/guide/topics/security/normal-permissions.html

Here's the official Google short video on moving to runtime permissions:
https://www.youtube.com/watch?v=iZqDdvhTZj0

### PR DESCRIPTION
**Pull request by barbeau**
Here's a full list of permissions we currently use from `AndroidManifest.xml`.  As I document the [protection level](https://developer.android.com/guide/topics/permissions/overview#normal-dangerous) and implement fixes (see runtime-permissions branch) I'll check them off.  Only "Dangerous" permissions require code changes.

- [x] `<uses-permission android:name="android.permission.INTERNET"/>` - Normal
- [x] `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>` - Dangerous
- [x] `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` - Dangerous
- [x] `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` - Normal
- [x] `<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>` - Normal
- [x] `<uses-permission android:name="android.permission.WAKE_LOCK"/>` - Normal
- [x] `<uses-permission android:name="android.permission.VIBRATE"/>` - Normal
- [x] `<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>` - Normal
- [x] `<uses-permission android:name="${applicationId}.permission.TRIP_SERVICE"/>` - OBA custom
- [x] `<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>` - Google C2D Messaging (Embedded Social SDK)
- [x] `<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>` - Google C2D Messaging (Embedded Social SDK)
- [x] `<uses-permission android:name="android.permission.READ_PHONE_STATE"/>` - Dangerous
- [x] `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` - Dangerous
- [x] `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` - Dangerous

### CODE REVIEW

**Comment by barbeau** [comment]
@acrown-msft Are the following permissions still needed in OBA for Embedded Social SDK?

~~~
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>
~~~

IIRC you mentioned that you're no longer using Google Cloud-to-device messaging in the ES SDK.

**Comment by acrown-msft** [comment]
No. It looks like those should be removed as part of the upgrade to FCM.
https://developers.google.com/cloud-messaging/android/android-migrate-fcm

**Comment by barbeau** [comment]
Thanks @acrown-msft!  I'll remove those then.  It looks like the WAKE_LOCK permission existed prior to ES SDK integration so I'll leave that until I figure out why it exists (it looks like it pre-dates my work too).

**Comment by barbeau** [comment]
@acrown-msft I'm seeing this relatively frequently while testing this PR:

~~~
    Process: com.joulespersecond.seattlebusbot, PID: 21328
    java.lang.RuntimeException: Unable to create application org.onebusaway.android.app.Application: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.joulespersecond.seattlebusbot.BACKGROUND_INIT cmp=com.joulespersecond.seattlebusbot/com.microsoft.embeddedsocial.service.WorkerService (has extras) }: app is in background uid UidRecord{193ccd9 u0a700 CEM  idle procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6059)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.joulespersecond.seattlebusbot.BACKGROUND_INIT cmp=com.joulespersecond.seattlebusbot/com.microsoft.embeddedsocial.service.WorkerService (has extras) }: app is in background uid UidRecord{193ccd9 u0a700 CEM  idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
        at android.app.ContextImpl.startService(ContextImpl.java:1484)
        at android.content.ContextWrapper.startService(ContextWrapper.java:663)
        at com.microsoft.embeddedsocial.base.service.ServiceLauncher.launchService(ServiceLauncher.java:49)
        at com.microsoft.embeddedsocial.base.service.ServiceLauncher.launchService(ServiceLauncher.java:39)
        at com.microsoft.embeddedsocial.sdk.EmbeddedSocial.init(EmbeddedSocial.java:102)
        at org.onebusaway.android.app.Application.setUpSocial(Application.java:581)
        at org.onebusaway.android.app.Application.onCreate(Application.java:111)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
~~~

It seems to happen when I re-start the app from Android Studio after making a code change.  I'm not sure if this happens when launching the app when tapping on the icon on the device.

Have you seen this before?

**Comment by acrown-msft** [comment]
I have not seen this before. Did this start appearing after some of the permissions were changed?

**Comment by barbeau** [comment]
@acrown-msft yes, I've only seen this since switching to runtime permissions. It also occasionally crashes when I'm not active using the app - I haven't used the app all day today but I just got a "OneBusAway has stopped" error dialog in the middle of doing something totally unrelated.

I'm guessing relates to permissions and not being allowed to launch a service in the background from error message:
`Not allowed to start service... app is in background"

Could you troubleshoot this? Getting a release with runtime permissions implemented is a priority right now for us.

**Comment by barbeau** [comment]
@acrown-msft From some quick Googling, it looks like this is permissions-related after targeting Oreo:
https://stackoverflow.com/a/46445436/937715

From skimming it looks like transitioning to the [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) instead of a Service is the "right" way to fix this.

**Comment by barbeau** [comment]
@acrown-msft I opened a separate issue for the ES SDK crash because it's not related to runtime permissions but instead Oreo background execution - https://github.com/OneBusAway/onebusaway-android/issues/933.  We can continue discussion there.

**Pull request merged**
