### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### OneBusAway/onebusaway-android now has a Chat Room on Gitter

@barbeau has just created a chat room. You can visit it here: [https://gitter.im/OneBusAway/onebusaway-android](https://gitter.im/OneBusAway/onebusaway-android?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/OneBusAway/onebusaway-android?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by barbeau** [comment]
Going to try this and see how it works for chat.

**Comment by bbodenmiller** [comment]
@barbeau can we try this on the iPhone repo too? (Owner or collaborator has to setup)

/cc @aaronbrethorst

**Comment by barbeau** [comment]
I'll leave trying Gitter for OBA iOS up to @aaronbrethorst.  If he wants to use it and can't flip the switch himself just let me know and I'll do it.

**Comment by aaronbrethorst** [comment]
done n' done

**Pull request merged**
