### PR TITLE
Added themed icon support with monochrome icon.

### PR DESCRIPTION
**Pull request by kungharrison**
Support for themed icons for Android 13+. I kept the monochrome version identical to the original icon, just with added transparency.

Changes:
ic_launcher_monochrome.xml: Modified the original logo svg with transparency using Inkscape
ic_launcher.xml: Added monochrome icon support
ic_launcher_round.xml: Added monochrome icon support

Screenshots:
Default Icon (will still be used if themed icon is turned off or not supported in API < 33)
image
Themed Icon (Red & Day) 
image
Themed Icon (Red & Night)
image
Themed Icon in on Device
image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything
- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
thanks @kungharrison! I'm supposed to be receiving an Android 14 device in the mail soon (USPS lost the first one 🙄, but thankfully the vendor's being cool about it and is supposed to ship me another one tomorrow). I'd like to review this on a device before merging, so it will be a few days, but it's on my radar! Please ping me if you haven't seen this get merged within a week.

**Comment by kungharrison** [comment]
@aaronbrethorst Hmm, I'm not sure why it's failing the tests, I ran the tests locally and it worked fine, plus there's really no change in code that should cause all the test to fail. It seems all the tests are getting skipped, maybe there's a problem with the CI pipeline?

**Comment by aaronbrethorst** [comment]
"Failing after 360m"

Sounds like something went wrong in the pipeline. I'll try running it again.

**Comment by kungharrison** [comment]
@aaronbrethorst Unfortunately it still seems to not be working. There seems to be an error with the emulator starting up, I see these lines stating the emulator is out of date that weren't happening with my previous pull request.

Current pull request failed test:
image
Past pull request successfully run:
image

Then it seems to start throwing a bunch of errors and never reaches the "Emulator booted." stage, so I think the issue with the tests timing out at 6 hours might have something to do with that?

Current pull request failed test:
image
Past pull request successfully run:
image

**Comment by kungharrison** [comment]
At this point I'm wondering if the tests are failing is because <monochrome> is supported in API level 33+?

**Comment by aaronbrethorst** [comment]
@kungharrison hmm, that's an interesting angle to explore. I'll investigate.

**Comment by aaronbrethorst** [comment]
I'll merge this in #1118

**Pull request closed without merging**
