### PR TITLE
Fix #278 - Check Situation active windows before displaying Alerts

### LINKED ISSUE #278: Active time windows of Alerts (i.e., Situations) aren't respected
Reported on the [OBA Dev list](https://groups.google.com/forum/#!topic/onebusaway-developers/GWiGsMzae94):

>I am having issue with old alerts still showing up on Android phone. Looking at the '/api/where/arrivals-and-departures-for-stop' there is 'data.references/situations.activeWindows' element but I do not find any code that checks these values on Android.

>Is there update / patch available for this?

If we can get a hold of a response that includes this info we can add support for it in OBA Android.

### PR DESCRIPTION
**Pull request by barbeau**
Includes @softrunit's fix from #278, but refactored here to allow for unit tests.  Unit tests for agencies that include active windows and those that do not are included in this PR.

### CODE REVIEW

**Comment by barbeau** [comment]
@softrunit Please review to make sure this still works for you.

**Comment by barbeau** [comment]
@softrunit Just wanted to ping you again on this.  Would you be able to do a quick review on this revised PR so we can get it merged?

**Comment by softrunit** [comment]
Sean, we are on vacation in Vail coming home tonight. If this can wait till
tomorrow morning I can do it then. Cheers, Mike

**Comment by barbeau** [comment]
That's fine, no rush.

**Comment by softrunit** [comment]
@barbeau refactoring makes sense, and all changed files look good to me. Thank you!

**Comment by barbeau** [comment]
Thanks @softrunit!  And thanks for finding this bug!

**Pull request merged**
