### PR TITLE
spanish translations based on English arrays and strings files

### PR DESCRIPTION
**Pull request by themonki**
Hi,

I translate to Spanish (based on Latin America terms).

I don't translate the key `main_help_whatsnew`. When you decide that is placed there I can do the translation.

### CODE REVIEW

**Comment by barbeau** [comment]
Awesome, thanks @themonki!  This is great.  I'll see if I can get a new Alpha version out soon with this translation so you can test it.

I'll ping you again when `main_help_whatsnew` is updated.  For the public v2.0 release, it's likely that "What's New" dialog will actually be replaced by the tutorial I'm currently working on (https://github.com/OneBusAway/onebusaway-android/issues/313).  More strings will be added as part of this tutorial, so I'll ping you when this is complete as well.

**Comment by themonki** [comment]
Excellent news of the tutorial, I will be pending @barbeau.

**Comment by barbeau** [comment]
@themonki I just finished the tutorial implementation for OBA Android - you can see the files (and strings) that were added/changed here:
https://github.com/CUTR-at-USF/onebusaway-android/commit/c084befb0ec9e3caf5dc82448869bcf842c31712

Would you be able to put together the Spanish translation for these, and open a new pull request with them?

I'd like to start pushing out a beta next week.  I have one or two items to clean up, but should be very soon.

**Comment by themonki** [comment]
@barbeau i hope doing the pull request for tomorrow

**Pull request merged**
