### PR TITLE
Tutorial fragment implementation

### PR DESCRIPTION
**Pull request by cagryInside**
New `TutorialFragment` displays tutorial information from a string and resource array.

### Example Usage

1 - Define a string and resource array in the `array.xml`

```
    <!-- Resource array -->
    <array name="report_types_icons_without_open311">
        <item>@drawable/stop_issue_tutorial_0</item>
        <item>@drawable/stop_issue_tutorial_2</item>
        <item>@drawable/stop_issue_tutorial_3</item>
    </array>

    <string-array name="preferred_units_options">
        <item>@string/preferences_preferred_units_option_automatic</item>
        <item>@string/preferences_preferred_units_option_metric</item>
        <item>@string/preferences_preferred_units_option_imperial</item>
    </string-array>
```

2 - Pass this arrays as parameters

```
        TutorialFragment tutorialFragment = new TutorialFragment();
        Bundle bundle = new Bundle();
        // Set string resources from arrays
        bundle.putInt(TutorialFragment.STRING_RESOURCE_ID, R.array.preferred_units_options);
        // Set image resources from arrays
        bundle.putInt(TutorialFragment.IMAGE_RESOURCE_ID, R.array.report_types_icons_without_open311);
        tutorialFragment.setArguments(bundle);
```

3 - Show fragment
```
        getSupportFragmentManager().beginTransaction().replace(R.id.main_fragment_container, tutorialFragment).commit();
```

### Sample Screenshots

device-2015-10-19-223836
device-2015-10-19-223944
device-2015-10-19-223959

### Notes 

* I only test this fragment with `Motorola Nexus 6`
* I will be testing with HTC EVO 3D

### CODE REVIEW

**Comment by cagryInside** [comment]
Views look good with HTC Evo 3D. However, we are getting `java.lang.OutOfMemoryError` if images are large. Adding `android:largeHeap="true"` property to manifest fixes this problem, but we might not want to increase the heap size. @barbeau what do you think?

**Comment by barbeau** [comment]
@cagryInside I was wondering if we'd have issues with image sizes, both in terms of increasing the size of the APK and memory issues.  

A few questions:

1. How large are image sizes that trigger the `java.lang.OutOfMemoryError` (and for how many images)?  
2. What's the increase in APK size for the images (and for how many images)?
3. What's the increase in app memory when opening this fragment (and for how many images)?
3. Are these PNGs?

We may need to scale down the images, and/or use JPEGs instead.

**Comment by barbeau** [comment]
BTW, thanks for your work on this.  It's a great feature.

**Comment by barbeau** [comment]
Thanks @cagryInside!

**Pull request merged**
