### PR TITLE
Fix #840 - Hide the social UI items when custom API URL is entered

### LINKED ISSUE #840: ES - NPE when using social features when custom server API is added
**Summary:** 

If you add a customer server API via "Settings->Advanced->OneBusAway API Server" and then click on the buttons to access the stop/route social threads, you'll get an NullPointerException because a region isn't currently selected.

We should hide the ES features after the user manually enters a custom OBA server API, similar to how we hide them if the region has `supportsEmbeddedSocial` as `false` in the Regions API.

Stops:

~~~
java.lang.NullPointerException: 
  at org.onebusaway.android.ui.ArrivalsListFragment.openStopDiscussion (ArrivalsListFragment.java:822)
  at org.onebusaway.android.ui.ArrivalsListHeader$4.onClick (ArrivalsListHeader.java:455)
  at android.view.View.performClick (View.java:6261)
  at android.view.View$PerformClick.run (View.java:23748)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
~~~

Routes:

~~~
java.lang.NullPointerException: 
  at org.onebusaway.android.ui.ArrivalsListFragment.openRouteDiscussion (ArrivalsListFragment.java:813)
  at org.onebusaway.android.ui.ArrivalsListAdapterStyleB$4.onClick (ArrivalsListAdapterStyleB.java:206)
  at android.view.View.performClick (View.java:6261)
  at android.view.View$PerformClick.run (View.java:23748)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
~~~

**Steps to reproduce:** 

1. Enter the URL of an OBA server (e.g., `http://api.tampa.onebusaway.org`) as a custom server API via "Settings->Advanced->OneBusAway API Server"

For stops:
2. View arrivals for a stop, and then click on the "Join discussion" social icon to the right of the stop name

For routes:
2. View arrivals for a stop, and then click an arrival time, and then click on the "Join discussion" option

**Expected behavior:** 

After entering a custom server API, the embedded social options should be hidden

**Observed behavior:** 

After entering a custom server API, the embedded social options are visible and throw an NPE when tapping on the stop/route "Join discussion" buttons

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 beta

**Screenshots:** 

N/A

### PR DESCRIPTION
**Pull request by barbeau**
@acrown-msft Could you please review?

This fixes https://github.com/OneBusAway/onebusaway-android/issues/840.

Thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by acrown-msft** [comment]
I'm still able to repro the bug and trigger a null pointer exception.

1. Select a region where social is enabled
2. Select a stop
3. Open the Settings page and enter a custom server URL
4. Navigate back twice (back to the home screen -- stop should still be selected)
5. Select discussion button

Hiding the social UI for custom servers is fine; however, I think this should be handled at the openStopDiscussion level where the exception occurs.  Pass an empty string along if the current region is null.  The EmbeddedSocial UI will display a message about not finding the discussion.  I've implemented this locally and can commit this to your branch if you'd like.

**Comment by barbeau** [comment]
@acrown-msft Ah, good catch.  Yes, we're not refreshing the layout of the ArrivalsListFragment within the HomeActivity when returning from the Settings (like we're doing for the NavigationDrawerFragment).

I don't believe you can commit directly to this branch due to access permissions, but if you just want to push the commit to a branch on Github and link to it here I can pull it in and push to this PR.

Thanks!

**Comment by barbeau** [comment]
To clarify, just add one more commit with your change to the branch for this PR, and then push that branch to your own Github repo and provide the link here.

**Comment by acrown-msft** [comment]
Branch with null check here: https://github.com/acrown-msft/onebusaway-android/tree/customApiUrl

**Pull request merged**
