### PR TITLE
Update whats new

### LINKED ISSUE #922: Spanish translation of "What's New"
**Summary:** 

@themonki Would you be able to translate the new "What's new" string today (see below or master branch)?  You can either just comment on this issue or submit a pull request.  I'm trying to get a bug fix out quickly.

Thanks!

~~~
    <string name="main_help_whatsnew">&#8226;\u0020
        <b>Route filter now affects alerts</b>
        - When viewing alerts at a stop, alerts for hidden routes are now hidden.\n&#8226;\u0020
        <b>Bug fixes</b>
        - See http://bit.ly/oba-android-releases
    </string>
~~~

### PR DESCRIPTION
**Pull request by themonki**
Please make sure these boxes are checked before submitting your pull request - thanks!

Fix #922

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by barbeau** [comment]
@themonki Looks like you last commit reverted the translation change?

**Comment by themonki** [comment]
Sorry, yes, I squash and force the push

**Comment by barbeau** [comment]
Thanks!  Looks good now.

**Comment by barbeau** [comment]
Thanks @themonki!

**Pull request merged**
