### PR TITLE
fix: Enhanced layout of "About" Activity

### LINKED ISSUE #1138: Enhancement: "About"Activity layout needs to be enhanced
**Summary:** 

layout of about page is unorganized.

**Steps to reproduce:** 

step-1: open setting
step-2: click on about.

**Expected behavior:** 

Should be in organized manner (material UI).

**Device and Android version:** 

Xiaomi 11i running Android 13 with the latest version of Google Play Services.

**Screenshots:** 
Before:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/259c40f4-5ca2-4852-b3db-d7934fdb9d05

After:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/11ad077c-c393-4379-9846-a6ab53cc586b

I'm Currently working this issue

### PR DESCRIPTION
**Pull request by sebesti0n**
fix #1138  

Follow Material UI design pattern.

After:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/262621fa-5cd7-4074-8a58-d8ac096f2a71

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
I like the idea, but I don't think hosting five different `MaterialTextView`s is the way to do it. Please instead take the existing `about_text` and turn it into an HTML page. Also, please make sure that the localized variants are also updated. thanks!

**Comment by sebesti0n** [comment]
> I like the idea, but I don't think hosting five different `MaterialTextView`s is the way to do it. Please instead take the existing `about_text` and turn it into an HTML page. Also, please make sure that the localized variants are also updated. thanks!

Okay, I will get it done.

**Comment by sebesti0n** [comment]
Implemented @aaronbrethorst  in a new pull request #1148.
Link-https://github.com/OneBusAway/onebusaway-android/pull/1148

**Review by shankarpriyank — COMMENTED** [review]
Hey, I am not a maintainer or stuff.
But I had a look at pr and though maybe my comments could be help.
Nothing too serious, just some thoughts to take with a grain of salt (or a pinch if you're feeling adventurous).

**Comment by sebesti0n** [comment]
> Hey, I am not a maintainer or stuff. But I had a look at pr and though maybe my comments could be help. Nothing too serious, just some thoughts to take with a grain of salt (or a pinch if you're feeling adventurous).

@shankarpriyank I've created a new pull request incorporating the suggested changes made by @aaronbrethorst.

**Comment by shankarpriyank** [comment]
Ahh sorry, never mind, when I had a look there were no other comments.
I guess there was a glitch somewhere!

**Pull request closed without merging**
