### PR TITLE
Fix #987: Toggle route filter from bus options menu

### LINKED ISSUE #987: Toggle "Show only this route" to "Show all routes" when filtering all other routes
**Summary:** 

Reported by a user:

>Hello- great app overall but I have some issues, all related to the "show this route only" feature.
>
>First, I can't figure out how to turn it off for a stop. The "show this route only" link should toggle to "show all routes".
>
>Second, this option persists across sessions and even reboots. I may not always want only a single route and will certainly forget that I selected that option, causing confusion and frustration for later trips. I would prefer that the option not persist across sessions. If a user wants this functionality, there should be a visual indication that a filter is on while viewing arrival times along with a way to turn it off.
>
>Currently, I have to delete the app data to get back to normal.

You can tap on an arrival time and then select "Show only this route", and then in the banner that appears at the top of the arrivals list that says "Showing 1 of 9 routes (show all)" you can tap on "(show all)", and it should show all the routes again at that stop.

However, it would be more obvious to the user if we toggle the menu option for "Show only this route" to "Show all routes" so if the user goes back to the same place they originally changed the option they can easily change it back.

**Steps to reproduce:** 

1. Tap on an arrival time and then select "Show only this route"
1. Tap on arrival time again

**Expected behavior:** 

Change the "Show only this route" to "Show all routes" to let the user reverse their initial operation

**Observed behavior:** 

"Show only this route" is displayed, and the user has to find another location in the app (the banner) to show all routes again.

**Device and Android version:** 

N/A

### PR DESCRIPTION
**Pull request by egconley**
Note - Hello!  This is my first contribution to OneBusAway.  I did run the unit tests, and testBuildTripOptions() in UIUtilTest does fail, but it also fails on the untouched code on the master branch of my forked repo.  I did  add an additional parameter to buildTripOptions(), so that parameter will need to be added in the test files when buildTripOptions() is called.  But, I'm hesitant to edit the tests as a newcomer to the code base, especially since that test fails without the code that I added.  Very excited to have had the opportunity to learn from the project and am open to any feedback to make this a helpful contribution!
  
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by barbeau** [comment]
@egconley Thanks for working on this! Let me take a look at the failing test and see if I can figure out what's going on.

**Comment by barbeau** [comment]
@egconley I ran the master branch `UIUtilTest` tests on a Samsung Galaxy S8+ with Android 9 as well as an API 28 emulator on a clean install and they pass. Let me know if you see different, and if so on what emulator API level or device and Android version.

From a quick scan of the Travis output, though, it looks like the failure for this PR is just a build failure? Maybe you just need to update the tests to pass in a `hasRouteFilter` variable and update the expected output for each test case? And maybe add a few new assertions for the case when the menu option should  say "show all routes"?

**Comment by egconley** [comment]
@barbeau Thanks for doing that.  hm, I ran the tests from master again and am still have the one test fail.  

My emulator details: Pixel 2 API 29 (AVD) - 10.  I'm not sure if the build variant matters, but I'm on `obaGoogleDebug`.  

I can definitely update the tests on my branch to incorporate the `hasRouteFilter` variable, but from what it looks like, `testBuildTripOptions` is failing on master because my options menu doesn't include `"Join discussion"`.  See below.
```
E/TestRunner: failed: testBuildTripOptions(org.onebusaway.android.util.test.UIUtilTest)
    ----- begin exception -----
    junit.framework.AssertionFailedError: expected:<8> but was:<7>
        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.failNotEquals(Assert.java:287)
        at junit.framework.Assert.assertEquals(Assert.java:67)
        at junit.framework.Assert.assertEquals(Assert.java:199)
        at junit.framework.Assert.assertEquals(Assert.java:205)
        at org.onebusaway.android.util.test.UIUtilTest.testBuildTripOptions(UIUtilTest.java:223)
...
    ----- end exception -----
I/TestRunner: finished: testBuildTripOptions(org.onebusaway.android.util.test.UIUtilTest)
I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
I/TestRunner: run finished: 12 tests, 1 failed, 0 ignored
```

And then if I comment out `assertEquals(8, options.size());` on line 223:
```
E/TestRunner: failed: testBuildTripOptions(org.onebusaway.android.util.test.UIUtilTest)
E/TestRunner: ----- begin exception -----
E/TestRunner: java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.util.ArrayList.get(ArrayList.java:437)
        at org.onebusaway.android.util.test.UIUtilTest.testBuildTripOptions(UIUtilTest.java:234)
```

**Comment by barbeau** [comment]
Ah - OK, I see what's happening. The Embedded Social key isn't configured on your machine, so it's not enabling the social features in the menu. 

If you add:

```
EMBEDDED_SOCIAL_API_KEY=xxxxxx
EMBEDDED_SOCIAL_TELEMETRY_KEY=xxxxxx
```

...in `gradle.properties` in the onebusaway-android folder as a workaround I think that should get the tests to pass. 

I'll work on fixing this in the master branch.

**Comment by barbeau** [comment]
Ok, I fixed the issue in https://github.com/OneBusAway/onebusaway-android/commit/fd7ef191a68000571f058ad8b5c2933c0faf4d28 in the master branch, so if you merge the master branch before changing the tests you hopefully shouldn't have any conflicts :crossed_fingers:

**Comment by egconley** [comment]
> Ok, I fixed the issue in [fd7ef19](https://github.com/OneBusAway/onebusaway-android/commit/fd7ef191a68000571f058ad8b5c2933c0faf4d28) in the master branch, so if you merge the master branch into this PR branch before changing the tests you hopefully shouldn't have any conflicts 🤞.; And everything should pass even if you don't have the key configuration I mentioned above.

@barbeau Thank you!  That worked, but I'm wondering if you have a git recommendation.  

Fetched and merged those changes to master, and the tests passed.  I rebased my egconley-issue987 feature branch, updated the tests to include the hasRouteFilter variable - all passing tests.  Squashed my commits and tried to push to egconley-issue987, but am getting rejected.  Any suggestions?  Including the log below as well.
```
Ellens-MacBook-Pro:onebusaway-android ellenconley$ git push origin egconley-issue987
To https://github.com/egconley/onebusaway-android.git
 ! [rejected]          egconley-issue987 -> egconley-issue987 (non-fast-forward)
error: failed to push some refs to 'https://github.com/egconley/onebusaway-android.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Ellens-MacBook-Pro:onebusaway-android ellenconley$ git log
commit 4c8bbfe1c6fcefabc9be31c9490e7d7e145d3d47 (HEAD -> egconley-issue987)
Author: egconley <31393715+egconley@users.noreply.github.com>
Date:   Tue Mar 10 21:08:14 2020 -0700

    fix for issue #987: toggle route filter from bus options menu, updated testBuildTripOptions to incorporate hasRouteFilter parameter

commit fd7ef191a68000571f058ad8b5c2933c0faf4d28 (upstream/master, master)
Author: Sean Barbeau <barbeau@cutr.usf.edu>
Date:   Thu Mar 12 11:45:26 2020 -0400

    Fix #1031 - Check for Embedded Social key in UIUtils tests
    
    * Also add info on configure ES SDK key in build docs

commit ca253210471ec9f75dbd9f57369c1250b87ead9c
Author: Sean Barbeau <sjbarbeau@gmail.com>
Date:   Wed Mar 11 14:50:04 2020 -0400

    Fix #1027 - Trim whitespace from route short names

commit 796f6a180ce129678d26d7a68cbbee88efe3207c (origin/master, origin/HEAD)
Author: Sean Barbeau <barbeau@cutr.usf.edu>
Date:   Fri Feb 28 17:38:25 2020 -0500

    Fix #1014 - Reimplement "bus only" and "rail only" trip planning options
    
    * Change to new OTP constants for bus only (BUS) and rail only (RAIL) instead of BUSISH and TRAINISH
    * Fix mapping of Additional Trip Preferences mode selection in the UI to the mode array
    * Don't send "max walk distance" parameter in the API request if it isn't set by the user in the UI
```

**Comment by barbeau** [comment]
@egconley If you rebase a branch, it changes the Git history for that branch. After that, you can't do a simple `push` because your local history and the PR branch history have diverged.  Given your current state, the easiest solution would be just to do a "force push" (using Android Studio UI, or the `-f` parameter from command line) to overwrite the GitHub PR branch on your fork with your local branch. Just make sure your local branch looks good before you do this to avoid losing any changes.

In the future, if you want to avoid having to overwrite the PR branch you could have `merge`d the master branch into your local branch instead of doing a rebase (`git merge` retains the existing branch history). So (assuming you have the main OneBusAway/onebusaway-android repo as a remote `upstream` and your fork on GitHub as a remote `origin`):

~~~
git checkout master
git pull upstream master // Update your local master branch to the changes I made in the main repo master branch
git checkout egconley-issue987 // Switch back to your PR branch
git merge master // Merge the changes I made in the main repo to your PR branch
~~~

..and then you can just continue to add commits to the same branch and push to `origin`, and each new commit will show up in this PR.

**Comment by egconley** [comment]
@barbeau Awesome, taking note to merge next time and went ahead and force pushed.

**Comment by egconley** [comment]
> @egconley Thanks, this is looking really good!!
> 
> There is only one situation that still needs to be covered.
> 
> If you start with a complete route list for a stop like a transit center that has more than two routes:
> 
> 1. Tap on the 3 dots overflow menu
> 2. Tap on "Filter routes"
> 3. Check two routes and select ok
> 4. Tap on an arrival info card and select "Show all routes"
> 
> At this point we would expect all routes to be shown - however, instead it shows only the route that you tapped on.

@barbeau Ah, gotcha!  Just pushed up a fix.

**Comment by barbeau** [comment]
@egconley Thanks, this looks great! Thanks for the contribution! Feel free to open another PR to add your name to the contributors list in the "About" section.

**Pull request merged**
