### PR TITLE
Upgrade Target SDK to 34 and fix foreground services compatibility with Android 14

### PR DESCRIPTION
**Pull request by amrhossamdev**
Releted to #1228 & #1230 and #1231 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
@amrhossamdev is this ready for review?

**Comment by amrhossamdev** [comment]
> @amrhossamdev is this ready for review?

No, I will finish #1231 and I will request a review

**Comment by amrhossamdev** [comment]
Ready for review @aaronbrethorst

**Review by aaronbrethorst — APPROVED** [review]
great work 👍

**Pull request merged**
