### PR TITLE
Update ES SDK to have unobfuscated stack traces

### PR DESCRIPTION
**Pull request by acrown-msft**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by acrown-msft** [comment]
I was unable to get the test suite to run properly on the master branch on my machine.

**Comment by barbeau** [comment]
@acrown-msft Did you try to run tests from command line or Android Studio?  If Android Studio, what version are you using?

Google finally removed the deprecated `AndroidTestCase` that our tests were based on (see https://github.com/OneBusAway/onebusaway-android/issues/874), which broke all of our tests.  I had to overhaul the test suite to use Android Testing Support Library.  I believe this requires the latest version of Android Studio, and you'll also probably need to delete your exiting run configurations for the tests from Android Studio, and then right-click on folder and choose "Run All Tests" again so it re-creates the configuration.

Regardless, I was able to run the unit tests in my Android Studio (v3.1.2) for this PR, and they all passed (with the exception of https://github.com/OneBusAway/onebusaway-android/issues/881, which is an unrelated configuration issue).

**Comment by acrown-msft** [comment]
Ah, looks like I was running into issue #881 with the "No runnable methods" error.

**Comment by acrown-msft** [comment]
I was running the test from the Android Studio terminal. Android Studio version 3.1.2.  The result is the same when I select "Run All Tests" by right clicking the test folder.

**Comment by barbeau** [comment]
Hmmm...you might need to clean and rebuild if you haven't done that yet.  And delete your existing run configurations for tests:

image

You can also try "File->Invalidate Caches and Restart".

**Pull request merged**
