### PR TITLE
Spanish translate

### PR DESCRIPTION
**Pull request by themonki**
I @barbeau,

i translate the tutorial and some tweak text.

I addition on strings.xml the key tutorial_button_text for reference in styles.xml, for the button "Got it" of tutorial.

I am tested and looks great tutorial!

### CODE REVIEW

**Comment by themonki** [comment]
For reference on #410.

**Comment by barbeau** [comment]
Thanks @themonki, looks great!

**Comment by barbeau** [comment]
@themonki I changed/added a few strings today - you can see these at https://github.com/OneBusAway/onebusaway-android/commit/8baa6bbe3e08fa0dac46746d0072112871d316c8 and https://github.com/OneBusAway/onebusaway-android/commit/68e1db6ca0309286ebb90f0516f55da18770d59a.  If you have time to translate these that would be great - if not, no big deal.  This should be the last change before release.

**Comment by themonki** [comment]
@barbeau Yes, I have no problem. Give me some hours.

**Pull request merged**
