### PR TITLE
Fix #254 - Automate updating of Amazon build flavor classes based on Google build flavor

### LINKED ISSUE #254: Better management of amazon/google build flavors common code
With the addition of support for the Amazon Fire Phone (#158), we now have two platform build flavors in the following packages:

* `src/google/java/org/onebusaway/android/map`
* `src/amazon/java/org/onebusaway/android/map`

With the exception of `ProprietaryMapHelpV2`, all other classes in these two packages are identical, except that they import classes from the amazon/google packages for the respective Maps APIs and reference the Amazon/GoogleMap object.

Here's our current manual process for maintaining these files:

>If changes are made to classes in src/google/java/org/onebusaway/android/map package, the same classes should be copied to src/amazon/java/org/onebusaway/android/map package.  Then, the Google classes should be replaced with equivalent Amazon classes as specified in http://bit.ly/AmazonMapsMigration. NOTE:  When doing this copying, ProprietaryMapHelpV2 should not need to be copied. It's specific to each platform.

We should be able to do better than manually copying/changing files.  I see two approaches:

1. Refactor these classes behind a common interface - I started down this path, but this gets ugly quick, since there is substantial logic in `BaseMapFragment` and `StopOverlay` that relies on the core classes used in the respective Maps APIs.  The result is interfaces for all the Maps API v2 classes, and its not clear to me that this is even possible due to the underlying management of SupportMapFragment, which is native to the Maps API, as well as the callbacks for detecting taps on a Marker, which are generated by the platform and provide a Marker Maps API v2 object.
2. Script the copy/replace logic - we should be able to accomplish this using Gradle and the `filterOnCopy` task - http://gradle.org/docs/current/userguide/userguide_single.html#filterOnCopy.  We would set this up so we'd edit the Google flavor classes, and then the Amazon classes would be auto-generated on the first Gradle build following the edit.  We'd also need to add some warning text of "this class is auto-generated, please don't edit" to the top of the Amazon package classes.

The second option seems like the simpler approach that keeps the code the cleanest, so I'm going to look into it further.

### PR DESCRIPTION
**Pull request by barbeau**
This PR implements scripting of the copy/replace logic to update the classes in the Amazon build flavor maps package (`src/amazon/java/org/onebusaway/android/map`) based on changes to the Google build flavor maps package (`src/google/java/org/onebusaway/android/map`), as a solution to #254.  It makes the following changes to the Amazon classes after copying the Google classes:

* `com.google.android.gms.maps` is changed to `com.amazon.geo.mapsv2`
* `GoogleMap` is changed to `AmazonMap`
* A header is added to the Amazon classes with a "do not manually change" message to indicate that those files should always be automatically generated based on changes to the Google classes.

Gradle copy, filter, and incremental changes features are used to script the process in `build.gradle`.  The only class that isn't automatically copied is `ProprietaryMapHelpV2`, since this class contains code specific to each build flavor.

Expected behavior is that without any changes to the Google build flavor map package classes, in the Gradle console (visible in Android Studio or on command line) towards the top of the build you should see the line:

`:onebusaway-android:copyMapsApiV2Classes UP-TO-DATE`

This means that no copying has taken place and the build is taking place as normal.

However, if a class in the Google build flavor map package is changed (excluding `ProprietaryMapHelpV2`), then you should see:

`:onebusaway-android:copyMapsApiV2Classes`

...which means that the `copyMapsApiV2Classes` task in `build.gradle` is executing.  And, after the build finishes, you should see the changes you made in the Google class reflected in the respective Amazon class.  So, when you go to commit the changes, the identical changes should be seen for the same Amazon and Google classes.

@cagryInside Could you please give this a quick look to make sure its working as intended on your machine?  It seems to work fine for me, but I'm also somewhat sleep-deprived :).  After this is merged to develop, if you rebase your work in #255 on this it should automatically copy your changes to `BaseMapFragment` in the Google folder to the Amazon folder.  You should also probably keep a separate backup of your work in another branch just in case something goes horribly wrong with this patch :).

### CODE REVIEW

**Comment by cagryInside** [comment]
> @cagryInside Could you please give this a quick look to make sure its working as intended on your machine? It seems to work fine for me, but I'm also somewhat sleep-deprived :). After this is merged to develop, if you rebase your work in #255 on this it should automatically copy your changes to BaseMapFragment in the Google folder to the Amazon folder. You should also probably keep a separate backup of your work in another branch just in case something goes horribly wrong with this patch :).


@barbeau I look at the code, and IMO it looks good. Furthermore, I checkout this PR, and tested with couple cases on my machine. I haven't found any problems. I would also like to check the changes on Amazon device, however I left the device at CUTR. I will do my final tests with the amazon device tomorrow and let you know, thanks.

**Comment by cagryInside** [comment]
@barbeau I run further tests on Amazon phone. It looks working fine.

**Comment by cagryInside** [comment]
Also, I notice that the license header is missing in ```ProprietaryMapHelpV2``` for both [google](https://github.com/OneBusAway/onebusaway-android/blob/copyMapsFiles/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/ProprietaryMapHelpV2.java)  and [amazon](https://github.com/OneBusAway/onebusaway-android/blob/copyMapsFiles/onebusaway-android/src/amazon/java/org/onebusaway/android/map/googlemapsv2/ProprietaryMapHelpV2.java)  versions.

**Comment by barbeau** [comment]
Thanks @cagryInside!  I'll push a commit to develop shortly (outside of this PR) that fixes the license headers on `ProprietaryMapHelpV2`.

**Comment by barbeau** [comment]
Ok, license header is added in https://github.com/OneBusAway/onebusaway-android/commit/96a291cf590cacb05ab9e373f1cac690b009e654.  Thanks @cagryInside for noticing this!

**Pull request merged**
