### PR TITLE
Fix #596: Update Spanish translation

### LINKED ISSUE #596: Update Spanish translation
@themonki Sorry, two more strings, if you have a moment:

~~~
    <string name="location_security_exception_title">Location permissions denied</string>
    <string name="location_security_exception_message">It looks like you may have denied location
        permissions for the app via the system settings. Location services will not be available.
        If you\'d like to re-enable location permissions, go to your Android system settings, choose
        OneBusAway and then Permissions, and re-enable Location.
    </string>
~~~

### PR DESCRIPTION
**Pull request by themonki**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Sign the [electronic OBA ICLA](https://docs.google.com/forms/d/12jV-ByyN186MuPotMvxJtNKtSaGGTnEHm8rXomM2bm4/viewform)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

- Addition location permissions translation
- Adition by comment https://github.com/OneBusAway/onebusaway-android/issues/596#issuecomment-232739788

### CODE REVIEW

**Comment by themonki** [comment]
@barbeau looks travis have some problem?

`Hang tight, the log cannot be shown until the build has started.`

**Comment by themonki** [comment]
Never mind, is working right now.

**Comment by barbeau** [comment]
Yes, initial build stalled, but I restarted it and hopefully it passes this time.

**Comment by barbeau** [comment]
Looks good, thanks @themonki!

**Pull request merged**
